### ISSUE TITLE
Showing error when open the model.xml file

### ISSUE THREAD

**Issue by LionelAvik** [fermi-lat/modelEditor#1]
fermitools1.0.1
fermitoolsdata-0.16
I need a help regarding the ModelEditor command. Whenever I am using this command, I am getting the following error warning :  "UserWarning: Can't locate DS9 executable. Please add the DS9 directory to your PATH and try again ".

I have already installed ds9 and have given a proper path ( home/Software) in the bashrc. The ds9 command is working fine. I am not sure how to add the ds9 to my working directory of fermilat.

Thanks in advance.

**Comment by donhorner** [comment]
Have you tried installing the pyDS9 package as described in the [Quickstart page](https://github.com/fermi-lat/Fermitools-conda/wiki/Quickstart-Guide#modeleditor)?

> The XML model editor GUI (called by the ModelEditor command) is dependent on the package pyDS9. Unfortunately, at this time this package is not available in the conda-forge anaconda cloud channel. In order to use this package you will need to install pyDS9 via pip, i.e. pip install pyds9. Once the installation is complete, ModelEditor should start without a problem.
